### PR TITLE
Switch poll-data-retrieval to OctoData

### PR DESCRIPTION
**Pull request by Rillke**
OctoData will be capable handling thousands of votes whereas single JSON dumps won't.

### CODE REVIEW

**Comment by Rillke** [comment]
Working fork: https://tools.wmflabs.org/octodata/dui/dui.html

**Comment by Rillke** [comment]
Meta poll not yet in DB but will be soon. POTY 2013 is right now.

**Comment by Rillke** [comment]
Now POTY 2012, POTY 2013 and Wikivoyage election 2013 are in. This issue was that I had to create new tables for meta (and any other wiki in future) because user names and ids only correlate to one wiki as SUL was not finalized when the poll was held. UNION SELECT turns out being to slow (or do I miss something?) so the results are merged in PHP. Not nice but fast.

**Comment by ricordisamoa** [comment]
I don't get https://tools.wmflabs.org/octodata/dui/dui.html working. Why?

**Comment by Rillke** [comment]
Frankly "I don't get xxx working" is not particularly helpful. Tested that and it works in IE, Opera and Firefox. Does it show a 404 error? Is the page served? Did you enter a user name and submitted? Which user name? Were results shown? Is an XHR send to https://tools.wmflabs.org/octodata/sucker.php?action=votelookup&username=Ricordisamoa&groupby=ballot ? If you follow the previous link, do you see the query results in JSON format? Did you try purging your cache? Are you on mobile?

**Comment by Rillke** [comment]
N.b. I am using `Ricordisamoa` as the user name and `meta.wikimedia` as the project.

**Comment by Rillke** [comment]
Is your [tool operating normal at your account](https://tools.wmflabs.org/ricordisamoa/dui/dui.html)? Did you add exceptions for your tool anywhere (browser, firewall, proxy)?

**Comment by ricordisamoa** [comment]
Oh, I was using "Jimbo Wales" as user name ;-)
But it should return data for other polls in which the user didn't vote (perhaps optionally), after that I will merge this request.
Thanks a lot for your hard work!

**Comment by Rillke** [comment]
{{done}}

**Comment by Rillke** [comment]
Oh, I see there is something else to do...

**Comment by Rillke** [comment]
Now really {{fixed}} and sorted by poll date.

**Comment by ricordisamoa** [comment]
I will integrate this patch in a future version of [dewkin](//github.com/ricordisamoa/dewkin), too.

**Comment by ricordisamoa** [comment]
Tick mark Deployed on the master site.

**Comment by Rillke** [comment]
Thank you! I'll delete the copy of DUI from octodata now.

**Pull request merged**
